### ISSUE TITLE
How to get the 2D image point (pixel) of the pointer tip? 

### ISSUE THREAD

**Issue by DearYong** [UCL/MPHY0026#49]
Hi, I read [this tutorial](https://mphy0026.readthedocs.io/en/latest/summerschool/pivot_calibration_demo.html#summerschoolpivotcalibration) and reproduced your project, and it works very well. Now I am very curious about this step: after we find the pointer offset through pivot calibration, how can we get the coordinate of the pointer tip in the 2D image? Can you briefly introduce the algorithm for this step or tell me where to find the code for this part of the logic? Thank you very much!

**Comment by thompson318** [comment]
Hello, great to hear it worked well for you. Once you have added the pointer tip location to the configuration file, like "pointer_tag_to_tip": "data/pointer_tip.txt",  you can rerun BARD with "sksurgerybard -c config.json" like you did when you acquired data for calibration. Now when you press 'd' BARD should create a new directory 'pointer_positions/bard_pointer_tips/'  and the estimated tip positions should be written there. 

See the function write_pointer_tip(self) in https://github.com/UCL/scikit-surgerybard/blob/master/sksurgerybard/algorithms/pointer.py for more information. Hope that is helpful. Let me know if you need more information.

**Comment by DearYong** [comment]
Thank you for your response. I am afraid you misunderstood me, what I am really curious about is how to convert 3D world points into 2D image points. In your project, I notice you used a silver sphere to indicate the estimated position of the pointer tip, so we need to know the 2D coordinate of the pointer tip in the image, or we cannot determine the position of the silver sphere, right? My question is how to obtain the 2D coordinate (pixel) of the pointer tip (silver sphere) in the image? Hope I have described my question clearly, and please correct me if my thinking is wrong.

**Comment by thompson318** [comment]
Hello, that makes it clearer thank you. We have no way of detecting the pointer tip itself in the 2D image. For the purpose of estimating the errors we just have to manually locate the marker tip. To get the estimated tip position (the silver sphere) we detect the ArUco tags in the 2D image, and calculate the 2D position of the pointer tip from them like this.
Step 1: We create a model (sphere) of the pointer tip, with the right offset based on the pivot calibration results. Line 113 of  https://github.com/UCL/scikit-surgerybard/blob/master/sksurgerybard/widgets/bard_overlay_app.py#L113
Step 2: We detect the ArUco tags on the pointer and use these to set the 2modelref of the pointer at Line 179 https://github.com/UCL/scikit-surgerybard/blob/master/sksurgerybard/widgets/bard_overlay_app.py#L179 . This gives us the 3D position of the pointer tip. 
The 3D position of the point is converted to a 2D on screen position when we call self.vtk_overlay_window.Render() which uses the camera projection matrix to project 3D points to 2D. The code for the renderer itself can be found at https://github.com/UCL/scikit-surgeryvtk/blob/master/sksurgeryvtk/widgets/vtk_overlay_window.py . More information about the camera projection matrix can be found in our earlier tutorial https://mphy0026.readthedocs.io/en/latest/summerschool/camera_calibration_demo.html#summerschoolcameracalibration
I hope that helps, let me know if anything is not clear.

**Comment by DearYong** [comment]
Thank you very much! This information is very helpful to me.
